model_path: "models/model.pkl"
model_download_params:
  gdrive_id: "1Sgpzrv2KU01vnynifIDVCi-Ca0wddhYZ"
  output_folder: "models/"
  zip_name: "model.pkl"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"