input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
downloading_params:
  gdrive_id: "1PiBD7lFKmGgX8fuaaeN-Q8_kXhaeEErO"
  output_folder: "data/raw/"
  zip_name: "downloaded.zip"
splitting_params:
  test_size: 0.2
  random_state: 123
train_params:
  model_type: "KNeighborsClassifier"
  model_params:
    n_neighbors: 5
  is_use_ml_flow: True
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"